{"uuid": "99cbde3e-4c60-4248-926d-cc642178fbc4", "children": ["74a4e81c-4c58-494f-8101-780c258b63e2"], "befores": [{"name": "_Class__pytest_setup_method", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=84.0.4147.105)\n\n", "trace": "  File \"d:\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 915, in call_fixture_func\n    fixture_result = next(generator)\n  File \"d:\\python\\lib\\site-packages\\_pytest\\python.py\", line 770, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"d:\\python\\lib\\site-packages\\_pytest\\python.py\", line 676, in _call_with_optional_argument\n    func()\n  File \"C:\\Users\\小白\\PycharmProjects\\UI_TEST_0823\\case\\mis\\test_mis_login.py\", line 11, in setup_method\n    self.driver.get(\"http://ttmis.research.itcast.cn/\")\n  File \"d:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"d:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1598437599702, "stop": 1598437599703}], "start": 1598437599702, "stop": 1598437599847}